/**
 * プログラミング用語データ
 * 流用しやすいように、単純な1つのフラットな配列として定義します。
 * id, term, reading, definition, category の形式。
 */
const programmingTerms = [
    // --- 基礎 (Basic) ---
    { id: "pg_001", term: "Variable", reading: "変数（へんすう）", definition: "値を一時的に保存するための名前付きのメモリ領域。", category: "プログラミング基礎" },
    { id: "pg_002", term: "Type", reading: "型（かた）", definition: "数値、文字列などデータの性質を定義するもの。", category: "プログラミング基礎" },
    { id: "pg_003", term: "Integer", reading: "整数型（せいすうがた）", definition: "小数点を含まない数値データ型。", category: "プログラミング基礎" },
    { id: "pg_004", term: "String", reading: "文字列型（もじれつがた）", definition: "文字の並びを表すデータ型。", category: "プログラミング基礎" },
    { id: "pg_005", term: "Boolean", reading: "真偽値（しんぎち）", definition: "真(true)または偽(false)の2値のみを持つ型。", category: "プログラミング基礎" },
    { id: "pg_006", term: "Constant", reading: "定数（ていすう）", definition: "一度代入すると値を変更できない変数。", category: "プログラミング基礎" },
    { id: "pg_007", term: "Initialization", reading: "初期化（しょきか）", definition: "変数に最初の値を代入すること。", category: "プログラミング基礎" },
    { id: "pg_008", term: "Identifier", reading: "識別子（しきべつし）", definition: "変数名や関数名など、要素を識別するための名前。", category: "プログラミング基礎" },
    { id: "pg_009", term: "Camel Case", reading: "キャメルケース", definition: "myVariableNameのように、単語の区切りを大文字にする命名規則。", category: "プログラミング基礎" },
    { id: "pg_010", term: "Snake Case", reading: "スネークケース", definition: "my_variable_nameのように、アンダースコアで繋ぐ命名規則。", category: "プログラミング基礎" },

    // --- 制御構造 (Control Structure) ---
    { id: "pg_011", term: "If Statement", reading: "If文", definition: "条件によって処理を分岐させる命令。", category: "制御構造" },
    { id: "pg_012", term: "Else Clause", reading: "Else節", definition: "Ifの条件に当てはまらなかった場合の処理。", category: "制御構造" },
    { id: "pg_013", term: "Switch Statement", reading: "Switch文", definition: "多数の値を比較して分岐させる命令。", category: "制御構造" },
    { id: "pg_014", term: "For Loop", reading: "Forループ", definition: "回数を指定して処理を繰り返すループ。", category: "制御構造" },
    { id: "pg_015", term: "While Loop", reading: "Whileループ", definition: "条件が満たされている間繰り返すループ。", category: "制御構造" },
    { id: "pg_016", term: "Infinite Loop", reading: "無限ループ", definition: "終了条件がなく永遠に繰り返される不具合。", category: "制御構造" },
    { id: "pg_017", term: "Break", reading: "ブレイク", definition: "ループ処理を途中で終了し、外へ抜ける命令。", category: "制御構造" },
    { id: "pg_018", term: "Continue", reading: "コンティニュー", definition: "ループの現在の回をスキップし、次の回へ進む命令。", category: "制御構造" },
    { id: "pg_019", term: "Nested Loop", reading: "ネスト（入れ子）", definition: "ループの中にさらにループがある構造。", category: "制御構造" },
    { id: "pg_020", term: "Conditional Operator", reading: "三項演算子", definition: "条件式 ? 真 : 偽 の形式で記述する簡略的なIf文。", category: "制御構造" },

    // --- 関数・メソッド (Functions) ---
    { id: "pg_021", term: "Function", reading: "関数", definition: "特定の処理をまとめて再利用可能にしたもの。", category: "関数" },
    { id: "pg_022", term: "Argument / Parameter", reading: "引数（ひきすう）", definition: "関数を呼び出す際に渡す値。", category: "関数" },
    { id: "pg_023", term: "Return Value", reading: "戻り値（もどりち）", definition: "関数の処理結果として呼び出し元に返す値。", category: "関数" },
    { id: "pg_024", term: "Invoke / Call", reading: "呼び出し", definition: "プログラム内で特定の関数を実行すること。", category: "関数" },
    { id: "pg_025", term: "Callback Function", reading: "コールバック関数", definition: "他の関数への引数として渡される関数。", category: "関数" },
    { id: "pg_026", term: "Anonymous Function", reading: "無名関数", definition: "名前を持たない関数。ラムダ式とも呼ばれる。", category: "関数" },
    { id: "pg_027", term: "Scope", reading: "スコープ", definition: "変数や関数が参照可能な有効範囲。", category: "関数" },
    { id: "pg_028", term: "Local Variable", reading: "ローカル変数", definition: "関数内でのみ有効な変数。", category: "関数" },
    { id: "pg_029", term: "Global Variable", reading: "グローバル変数", definition: "プログラム全体から参照可能な変数。", category: "関数" },
    { id: "pg_030", term: "Recursion", reading: "再帰（さいき）", definition: "関数が自分自身を呼び出すこと。", category: "関数" },

    // --- データ構造 (Data Structures) ---
    { id: "pg_031", term: "Array", reading: "配列", definition: "複数のデータを順番に並べて保持する型。", category: "データ構造" },
    { id: "pg_032", term: "Index", reading: "インデックス", definition: "配列の要素を特定するための番号（通常0から開始）。", category: "データ構造" },
    { id: "pg_033", term: "Object", reading: "オブジェクト", definition: "データと機能をセットにしたもの。", category: "データ構造" },
    { id: "pg_034", term: "Key / Property", reading: "キー / プロパティ", definition: "情報にアクセスするための「名前」。", category: "データ構造" },
    { id: "pg_035", term: "Dictionary / Map", reading: "連想配列（ディクショナリ）", definition: "キーと値をペアで紐付けるデータ構造。", category: "データ構造" },
    { id: "pg_036", term: "Stack", reading: "スタック", definition: "後入れ先出し(LIFO)のデータ構造。", category: "データ構造" },
    { id: "pg_037", term: "Queue", reading: "キュー", definition: "先入れ先出し(FIFO)のデータ構造。", category: "データ構造" },
    { id: "pg_038", term: "Linked List", reading: "連結リスト", definition: "各要素が次の要素への参照を持つ構造。", category: "データ構造" },
    { id: "pg_039", term: "Tree", reading: "木構造", definition: "階層的にデータを管理する構造（DOM treeなど）。", category: "データ構造" },
    { id: "pg_040", term: "Hash Map", reading: "ハッシュマップ", definition: "ハッシュ関数を用いて高速に検索できるデータ構造。", category: "データ構造" },

    // --- オブジェクト指向 (OOP) ---
    { id: "pg_041", term: "Class", reading: "クラス", definition: "オブジェクトの「設計図」。", category: "オブジェクト指向" },
    { id: "pg_042", term: "Instance", reading: "インスタンス", definition: "クラス(設計図)をもとに生成された実体。", category: "オブジェクト指向" },
    { id: "pg_043", term: "Constructor", reading: "コンストラクタ", definition: "インスタンス生成時に実行される初期化処理。", category: "オブジェクト指向" },
    { id: "pg_044", term: "Inheritance", reading: "継承（けいしょう）", definition: "既存のクラスの特徴を引き継いで新しいクラスを作ること。", category: "オブジェクト指向" },
    { id: "pg_045", term: "Encapsulation", reading: "カプセル化", definition: "データと処理をまとめ、細部を隠蔽すること。", category: "オブジェクト指向" },
    { id: "pg_046", term: "Polymorphism", reading: "多態性（ポリモーフィズム）", definition: "同じメソッド名でも、対象によって挙動が変わること。", category: "オブジェクト指向" },
    { id: "pg_047", term: "Abstraction", reading: "抽象化（ちゅうしょうか）", definition: "複雑な詳細を隠し、重要な特徴だけを抽出すること。", category: "オブジェクト指向" },
    { id: "pg_048", term: "Interface", reading: "インターフェース", definition: "実装すべきメソッドの構成（規約）を定義したもの。", category: "オブジェクト指向" },
    { id: "pg_049", term: "Override", reading: "オーバーライド", definition: "親クラスのメソッドを子クラスで上書きすること。", category: "オブジェクト指向" },
    { id: "pg_050", term: "Static", reading: "静的（スタティック）", definition: "インスタンス化せずに利用できるクラス固有の要素。", category: "オブジェクト指向" },

    // --- 開発工程・手法 (Dev Flow) ---
    { id: "pg_051", term: "Source Code", reading: "ソースコード", definition: "人間が書いたプログラムの文字情報。", category: "開発手法" },
    { id: "pg_052", term: "Compile", reading: "コンパイル", definition: "ソースコードをPCが理解できる形式に変換すること。", category: "開発手法" },
    { id: "pg_053", term: "Build", reading: "ビルド", definition: "コンパイルやリンクを行い、実行可能な形にすること。", category: "開発手法" },
    { id: "pg_054", term: "Debug", reading: "デバッグ", definition: "バグ(エラー)を見つけ、修正すること。", category: "開発手法" },
    { id: "pg_055", term: "Deployment", reading: "デプロイ", definition: "作成したプログラムを使えるように配置すること。", category: "開発手法" },
    { id: "pg_056", term: "Version Control", reading: "バージョン管理", definition: "コードの変更履歴を記録・管理すること。", category: "開発手法" },
    { id: "pg_057", term: "Refactoring", reading: "リファクタリング", definition: "動作を変えずにコードの内部構造をきれいにすること。", category: "開発手法" },
    { id: "pg_058", term: "Unit Test", reading: "単体テスト", definition: "個々の機能が正しく動くか検証するテスト。", category: "開発手法" },
    { id: "pg_059", term: "Pull Request", reading: "プルリクエスト", definition: "変更を反映してほしいと依頼する通知。", category: "開発手法" },
    { id: "pg_060", term: "CI / CD", reading: "シーアイ・シーディー", definition: "テストやデプロイを自動化する仕組み。", category: "開発手法" },

    // --- エラー・状態 (Errors) ---
    { id: "pg_061", term: "Bug", reading: "バグ", definition: "プログラムの誤りや不具合。", category: "エラー" },
    { id: "pg_062", term: "Syntax Error", reading: "構文エラー", definition: "文法が間違っている際に出るエラー。", category: "エラー" },
    { id: "pg_063", term: "Runtime Error", reading: "実行時エラー", definition: "実行中に予期せぬ事態で発生するエラー。", category: "エラー" },
    { id: "pg_064", term: "Exception", reading: "例外（れいがい）", definition: "本来想定していない事態が発生すること。", category: "エラー" },
    { id: "pg_065", term: "Null / Nil", reading: "ヌル（ニル）", definition: "「何も値が存在しない」ことを表す値。", category: "エラー" },
    { id: "pg_066", term: "Garbage Collection", reading: "ガベージコレクション", definition: "不要になったメモリを自動で解放する仕組み。", category: "エラー" },
    { id: "pg_067", term: "Stack Overflow", reading: "スタックオーバーフロー", definition: "メモリの上限を超えてエラーになること。", category: "エラー" },
    { id: "pg_068", term: "Deadlock", reading: "デッドロック", definition: "複数の処理が互いに待ち合い、停止してしまう状態。", category: "エラー" },
    { id: "pg_069", term: "Warning", reading: "警告", definition: "致命的ではないが注意が必要な通知。", category: "エラー" },
    { id: "pg_070", term: "Log", reading: "ログ", definition: "プログラムの実行記録をテキスト化したもの。", category: "エラー" },

    // さらに300語目標のため、主要言語・用語・Web技術などを一気にフラットに追加...
    { id: "pg_071", term: "JavaScript", reading: "ジャバスクリプト", definition: "Webブラウザで動作する中心的な言語。", category: "言語" },
    { id: "pg_072", term: "Python", reading: "パイソン", definition: "文法が簡潔で、AIやデータ分析に強い言語。", category: "言語" },
    { id: "pg_073", term: "PHP", reading: "ピーエイチピー", definition: "Webサイトのサーバ側処理に特化した言語。", category: "言語" },
    { id: "pg_074", term: "Ruby", reading: "ルビー", definition: "日本で開発された、直感的に書ける言語。", category: "言語" },
    { id: "pg_075", term: "Java", reading: "ジャバ", definition: "大規模システムやAndroid開発で使われる堅牢な言語。", category: "言語" },
    { id: "pg_076", term: "C#", reading: "シーシャープ", definition: "Microsoftが開発した。ゲームエンジンUnity等でも使用。", category: "言語" },
    { id: "pg_077", term: "TypeScript", reading: "タイプスクリプト", definition: "JSに型を追加した、より安全に開発できる言語。", category: "言語" },
    { id: "pg_078", term: "SQL", reading: "エスキューエル", definition: "データベースの操作に特化した言語。", category: "言語" },
    { id: "pg_079", term: "Swift", reading: "スイフト", definition: "Apple製品のアプリ開発に用いられる言語。", category: "言語" },
    { id: "pg_080", term: "Go", reading: "ゴー", definition: "Googleが開発した。高速で軽量なサーバサイド言語。", category: "言語" },
    { id: "pg_081", term: "Framework", reading: "フレームワーク", definition: "開発の土台となる枠組み（React, Rails等）。", category: "Web技術" },
    { id: "pg_082", term: "Library", reading: "ライブラリ", definition: "特定の便利な機能をまとめた部品。", category: "Web技術" },
    { id: "pg_083", term: "DOM", reading: "ドム", definition: "HTMLをプログラムから操作するための仕組み。", category: "Web技術" },
    { id: "pg_084", term: "API", reading: "エーピーアイ", definition: "アプリ同士が機能を共有するための繋ぎ目。", category: "Web技術" },
    { id: "pg_085", term: "AJAX", reading: "エイジャックス", definition: "ページを更新せずにデータ通信を行う手法。", category: "Web技術" },
    { id: "pg_086", term: "Async / Await", reading: "非同期（あしんく・あうぇいと）", definition: "時間がかかる処理を効率よく待つための書き方。", category: "Web技術" },
    { id: "pg_087", term: "JSON", reading: "ジェイソン", definition: "データのやり取りに使われる標準的なテキスト形式。", category: "Web技術" },
    { id: "pg_088", term: "CORS", reading: "コーズ", definition: "他のサイトからデータ取得を制御する仕組み。", category: "Web技術" },
    { id: "pg_089", term: "Frontend", reading: "フロントエンド", definition: "ユーザーの目に見えるブラウザ側の部分。", category: "Web技術" },
    { id: "pg_090", term: "Backend", reading: "バックエンド", definition: "サーバやデータベースなど、裏側の仕組み。", category: "Web技術" },

    // --- 続・プログラミング用語・最新ITなど (合計300語想定のサンプル) ---
    { id: "pg_091", term: "Database", reading: "データベース", definition: "大量のデータを保存・検索・管理する場所。", category: "IT全般" },
    { id: "pg_092", term: "Primary Key", reading: "主キー", definition: "データベース内でデータを一意に特定するための値。", category: "IT全般" },
    { id: "pg_093", term: "Query", reading: "クエリ", definition: "データベースに対する命令文のこと。", category: "IT全般" },
    { id: "pg_094", term: "Schema", reading: "スキーマ", definition: "データベースの構造や設計図。", category: "IT全般" },
    { id: "pg_095", term: "Transaction", reading: "トランザクション", definition: "一連の処理を「すべて完了」か「すべて取消」にする仕組み。", category: "IT全般" },
    { id: "pg_096", term: "Server", reading: "サーバ", definition: "データやサービスを提供する側のコンピュータ。", category: "IT全般" },
    { id: "pg_097", term: "Client", reading: "クライアント", definition: "ブラウザなど、サービスをリクエストする側の装置。", category: "IT全般" },
    { id: "pg_098", term: "IP Address", reading: "アイピーアドレス", definition: "ネット上の住所にあたる数値ラベル。", category: "IT全般" },
    { id: "pg_099", term: "DNS", reading: "ディーエヌエス", definition: "ドメイン名とIPアドレスを紐づける仕組み。", category: "IT全般" },
    { id: "pg_100", term: "Cloud", reading: "クラウド", definition: "物理サーバを持たず、ネット経由でIT機能を使うサービス。", category: "IT全般" },

    // ... (スペースの都合上、以降はデータパターンを一気に羅列しています) ...
    { id: "pg_101", term: "Docker", reading: "ドッカー", definition: "OS環境ごとパッケージ化して動かす「コンテナ」技術。", category: "インフラ" },
    { id: "pg_102", term: "Kubernetes", reading: "クバネティス", definition: "大量のコンテナを自動管理する仕組み。", category: "インフラ" },
    { id: "pg_103", term: "Ubuntu", reading: "ウブントゥ", definition: "開発でよく使われる人気のLinux OS系譜。", category: "インフラ" },
    { id: "pg_104", term: "SSH", reading: "エスエスエイチ", definition: "外部のサーバに安全に接続するための暗号化通信。", category: "インフラ" },
    { id: "pg_105", term: "Port", reading: "ポート", definition: "通信を受け付けるための専用の入口（番号）。", category: "インフラ" },
    { id: "pg_106", term: "Nginx", reading: "エンジンエックス", definition: "高速なWebサーバ用ソフトウェア。", category: "インフラ" },
    { id: "pg_107", term: "AWS", reading: "エーダブリューエス", definition: "Amazon Web Services。最大のクラウドサービス。", category: "インフラ" },
    { id: "pg_108", term: "Firebase", reading: "ファイアベース", definition: "Google提供のアプリ開発プラットフォーム。", category: "インフラ" },
    { id: "pg_109", term: "SSL / TLS", reading: "エスエスエル", definition: "通信を暗号化して盗聴を防ぐ仕組み（HTTPS）。", category: "インフラ" },
    { id: "pg_110", term: "Load Balancer", reading: "ロードバランサ", definition: "アクセスを複数のサーバに分散して負荷を減らす装置。", category: "インフラ" },

    { id: "pg_111", term: "Git", reading: "ギット", definition: "ファイルの変更履歴を管理する分散型ツール。", category: "バージョン管理" },
    { id: "pg_112", term: "Repository", reading: "リポジトリ", definition: "ソースコードや履歴を保存する場所。", category: "バージョン管理" },
    { id: "pg_113", term: "Commit", reading: "コミット", definition: "変更を履歴に記録（保存）すること。", category: "バージョン管理" },
    { id: "pg_114", term: "Branch", reading: "ブランチ", definition: "履歴の流れを枝分かれさせて管理すること。", category: "バージョン管理" },
    { id: "pg_115", term: "Merge", reading: "マージ", definition: "分かれたブランチの変更を統合すること。", category: "バージョン管理" },
    { id: "pg_116", term: "Clone", reading: "クローン", definition: "公開されたリポジトリを自分のPCへ複製すること。", category: "バージョン管理" },
    { id: "pg_117", term: "Push", reading: "プッシュ", definition: "自分のPCで行った変更を公開サーバへ送ること。", category: "バージョン管理" },
    { id: "pg_118", term: "Pull", reading: "プル", definition: "公開サーバの最新の変更を自分のPCに取り込むこと。", category: "バージョン管理" },
    { id: "pg_119", term: "Conflict", reading: "コンフリクト", definition: "同じ部分が別々に編集され、競合している状態。", category: "バージョン管理" },
    { id: "pg_120", term: "GitHub", reading: "ギットハブ", definition: "Gitを使った世界最大のコード共有プラットフォーム。", category: "バージョン管理" },

    // --- アルゴリズム・設計 ---
    { id: "pg_121", term: "Algorithm", reading: "アルゴリズム", definition: "問題を解くための効率的な手順。", category: "設計・理論" },
    { id: "pg_122", term: "Big O Notation", reading: "オーダー記法", definition: "アルゴリズムの実行速度や効率を表す指標。", category: "設計・理論" },
    { id: "pg_123", term: "Binary Search", reading: "二分探索", definition: "真ん中で分けて探し物を高速化するアルゴリズム。", category: "設計・理論" },
    { id: "pg_124", term: "Sort", reading: "ソート", definition: "バラバラのデータを特定の順序に並び替えること。", category: "設計・理論" },
    { id: "pg_125", term: "Design Pattern", reading: "デザインパターン", definition: "優れた設計ノウハウを型にしたもの。", category: "設計・理論" },
    { id: "pg_126", term: "UML", reading: "ユーエムエル", definition: "設計を視覚的に表すための統一的な図法。", category: "設計・理論" },
    { id: "pg_127", term: "Agile", reading: "アジャイル", definition: "短いサイクルで開発を繰り返す手法。", category: "開発プロセス" },
    { id: "pg_128", term: "Waterfall", reading: "ウォーターフォール", definition: "上流工程から下流へ順に進める伝統的な開発手法。", category: "開発プロセス" },
    { id: "pg_129", term: "Scrum", reading: "スクラム", definition: "チームで協力して進めるアジャイル開発の手法。", category: "開発プロセス" },
    { id: "pg_130", term: "MVP", reading: "エムブイピー", definition: "最小限の機能を持つ試作品。", category: "開発プロセス" },

    // --- セキュリティ ---
    { id: "pg_131", term: "Firewall", reading: "ファイアウォール", definition: "不正な通信をブロックする仕組み。", category: "セキュリティ" },
    { id: "pg_132", term: "Encryption", reading: "暗号化", definition: "データを特定の鍵で読めなく加工すること。", category: "セキュリティ" },
    { id: "pg_133", term: "Hash", reading: "ハッシュ値", definition: "元のデータから生成される一意の短い文字列。パスワード保存等に使用。", category: "セキュリティ" },
    { id: "pg_134", term: "Injection", reading: "インジェクション", definition: "悪意のある命令を流し込むサイバー攻撃。", category: "セキュリティ" },
    { id: "pg_135", term: "XSS", reading: "クロスサイトスクリプティング", definition: "Webサイトに罠のコードを埋め込む攻撃。", category: "セキュリティ" },
    { id: "pg_136", term: "Token", reading: "トークン", definition: "本人確認などに使われる使い捨ての引換証。", category: "セキュリティ" },
    { id: "pg_137", term: "Authorization", reading: "認可", definition: "何ができるか（権限）を確認し、許可すること。", category: "セキュリティ" },
    { id: "pg_138", term: "Authentication", reading: "認証", definition: "誰であるか（本人）を確認すること。", category: "セキュリティ" },
    { id: "pg_139", term: "Two-Factor Auth", reading: "二要素認証", definition: "PWの他にSMS等を使い、2段階で安全を高める方法。", category: "セキュリティ" },
    { id: "pg_140", term: "VPN", reading: "ブイピーエヌ", definition: "ネット上に仮想的な専用回線を作り、安全に通信する技術。", category: "セキュリティ" },

    // --- 最新トレンド・先端技術 ---
    { id: "pg_141", term: "Generative AI", reading: "生成AI", definition: "文章や画像を新しく生成できる人工知能。", category: "先端技術" },
    { id: "pg_142", term: "LLM", reading: "エルエルエム", definition: "大規模言語モデル。大量のテキストから学習したAI。", category: "先端技術" },
    { id: "pg_143", term: "Prompt Engineering", reading: "プロンプトエンジニアリング", definition: "AIから望む回答を得るための指示文の作り方。", category: "先端技術" },
    { id: "pg_144", term: "RAG", reading: "ラグ", definition: "AIに独自知識（外部データ）を追加して回答させる技術。", category: "先端技術" },
    { id: "pg_145", term: "DevOps", reading: "デブオプス", definition: "開発(Dev)と運用(Ops)が協力して効率化する手法。", category: "先端技術" },
    { id: "pg_146", term: "Microservices", reading: "マイクロサービス", definition: "巨大なアプリを小さな部品の集まりとして作る手法。", category: "先端技術" },
    { id: "pg_147", term: "Blockchain", reading: "ブロックチェーン", definition: "中央管理者がいない分散型の台帳技術。", category: "先端技術" },
    { id: "pg_148", term: "NFT", reading: "エヌエフティー", definition: "デジタルデータの所有権を証明する技術。", category: "先端技術" },
    { id: "pg_149", term: "Zero Trust", reading: "ゼロトラスト", definition: "「すべて信頼しない」を前提とするセキュリティの考え方。", category: "セキュリティ" },
    { id: "pg_150", term: "Edge Computing", reading: "エッジコンピューティング", definition: "近場でデータを処理し、速度を高める技術。", category: "先端技術" },

    // --- 追加データ (pg_151 - pg_300) -------------------------------------------------------------------
    // ここからは、より専門的な用語やプログラミング環境、周辺ツールを網羅します。
    { id: "pg_151", term: "OS", reading: "オーエス", definition: "WindowsやMac等、コンピュータの基本操作を司るソフト。", category: "IT基礎" },
    { id: "pg_152", term: "Linux", reading: "リナックス", definition: "オープンソースのOS。多くのサーバで採用されている。", category: "IT基礎" },
    { id: "pg_153", term: "Binary", reading: "バイナリ", definition: "0と1だけで表されたデータ形式。", category: "IT基礎" },
    { id: "pg_154", term: "Bit", reading: "ビット", definition: "データの最小単位。", category: "IT基礎" },
    { id: "pg_155", term: "Byte", reading: "バイト", definition: "8ビットを1つにまとめた単位。", category: "IT基礎" },
    { id: "pg_156", term: "Markdown", reading: "マークダウン", definition: "簡単な記号で文字装飾ができる書き方。", category: "IT基礎" },
    { id: "pg_157", term: "CLI", reading: "シーエルアイ", definition: "文字だけでコンピュータを操作する画面。", category: "IT基礎" },
    { id: "pg_158", term: "GUI", reading: "ジーユーアイ", definition: "マウスなどで視覚的に操作する画面。", category: "IT基礎" },
    { id: "pg_159", term: "Environment Variable", reading: "環境変数", definition: "OS全体で共有される設定値。", category: "IT基礎" },
    { id: "pg_160", term: "Path", reading: "パス", definition: "フォルダやファイルへの場所（道筋）。", category: "IT基礎" },

    { id: "pg_161", term: "Interpreter", reading: "インタプリタ", definition: "コードを1行ずつ翻訳しながら実行する方式。", category: "言語仕様" },
    { id: "pg_162", term: "Strong Typing", reading: "強い型付け", definition: "自動的な型変換を許さない厳格な仕様。", category: "言語仕様" },
    { id: "pg_163", term: "Dynamic Typing", reading: "動的型付け", definition: "実行時にデータの型が決まる仕様。", category: "言語仕様" },
    { id: "pg_164", term: "Static Typing", reading: "静的型付け", definition: "書くときにデータの型を固定する仕様。", category: "言語仕様" },
    { id: "pg_165", term: "Low-level Language", reading: "低水準言語", definition: "機械(ハード)に近い。C言語やアセンブラなど。", category: "言語仕様" },
    { id: "pg_166", term: "High-level Language", reading: "高水準言語", definition: "人間にとって読み書きしやすい。JSやRubyなど。", category: "言語仕様" },
    { id: "pg_167", term: "Native", reading: "ネイティブ", definition: "変換なしにそのまま動く、あるいは特定のOS専用のもの。", category: "言語仕様" },
    { id: "pg_168", term: "Runtime", reading: "ランタイム", definition: "プログラムの実行を支える補助ソフトの総称。", category: "言語仕様" },
    { id: "pg_169", term: "Memory Leak", reading: "メモリリーク", definition: "不要なメモリが残り続け、PCが重くなる不具合。", category: "言語仕様" },
    { id: "pg_170", term: "Callback Hell", reading: "コールバック地獄", definition: "処理の階層が深くなりすぎて読みづらくなる状態。", category: "言語仕様" },

    { id: "pg_171", term: "RegEx", reading: "正規表現（せいきひょうげん）", definition: "複雑な文字列パターンを記号で表す手法。", category: "プログラミング基礎" },
    { id: "pg_172", term: "Format", reading: "整形（フォーマット）", definition: "データの見た目を一定のルールに整えること。", category: "プログラミング基礎" },
    { id: "pg_173", term: "Cast", reading: "キャスト", definition: "あるデータ型を別の型へ強制的に変換すること。", category: "プログラミング基礎" },
    { id: "pg_174", term: "Null Safety", reading: "ヌル安全", definition: "Nullによるエラーを事前に防ぐプログラムの仕組み。", category: "プログラミング基礎" },
    { id: "pg_175", term: "Closure", reading: "クロージャ", definition: "周囲の変数を保持したまま振る舞う関数の仕組み。", category: "プログラミング基礎" },
    { id: "pg_176", term: "First-class Object", reading: "第一級オブジェクト", definition: "引数や戻り値にできる、JSにおける関数の扱い。", category: "プログラミング基礎" },
    { id: "pg_177", term: "Immutability", reading: "イミュータブル（不変性）", definition: "一度作った値を、後から書き換えないこと。", category: "プログラミング基礎" },
    { id: "pg_178", term: "Dependency", reading: "依存関係", definition: "動作に他のライブラリが必要な状態。", category: "プログラミング基礎" },
    { id: "pg_179", term: "Boilerplate", reading: "ボイラープレート", definition: "何度も使い回すお決まりの定型コード。", category: "プログラミング基礎" },
    { id: "pg_180", term: "Deprecated", reading: "非推奨", definition: "古くなり、将来的に廃止される予定の機能。", category: "プログラミング基礎" },

    { id: "pg_181", term: "SaaS", reading: "サース", definition: "クラウド上で動くソフトウェアそのもの。", category: "IT全般" },
    { id: "pg_182", term: "PaaS", reading: "パース", definition: "アプリ開発の「土台」をクラウドで借りること。", category: "IT全般" },
    { id: "pg_183", term: "IaaS", reading: "アイアース", definition: "計算リソース（サーバ、ネット等）をクラウドで借りること。", category: "IT全般" },
    { id: "pg_184", term: "Container", reading: "コンテナ", definition: "環境を丸ごと包んで、どこでも同じように動かす技術。", category: "インフラ" },
    { id: "pg_185", term: "Virtual Machine", reading: "仮想マシン(VM)", definition: "1つのPCの中にソフト等で複数のOSを作る技術。", category: "インフラ" },
    { id: "pg_186", term: "Websocket", reading: "ウェブソケット", definition: "双方向でリアルタイムな通信を可能にする技術。", category: "通信" },
    { id: "pg_187", term: "REST", reading: "レスト", definition: "Webシステム間のデータ連携における設計ルール。", category: "通信" },
    { id: "pg_188", term: "GraphQL", reading: "グラフキューエル", definition: "必要な項目だけを効率よく取得できるAPI規格。", category: "通信" },
    { id: "pg_189", term: "Endpoint", reading: "エンドポイント", definition: "APIを呼び出す際の特定のURL。", category: "通信" },
    { id: "pg_190", term: "Payload", reading: "ペイロード", definition: "通信で送られるデータ本体の部分。", category: "通信" },

    { id: "pg_191", term: "DOM Manipulation", reading: "DOM操作", definition: "JSなどでHTMLの見た目を動的に変えること。", category: "Web技術" },
    { id: "pg_192", term: "Single Page App", reading: "SPA", definition: "ページ遷移なしに動作するWebアプリ。", category: "Web技術" },
    { id: "pg_193", term: "PWA", reading: "プログレッシブWebアプリ", definition: "Webサイトをスマホアプリのように使える技術。", category: "Web技術" },
    { id: "pg_194", term: "Server Side Rendering", reading: "SSR", definition: "サーバ側で画面を作って送り、高速化する手法。", category: "Web技術" },
    { id: "pg_195", term: "Service Worker", reading: "サービスワーカー", definition: "ブラウザの裏側で働き、オフライン対応等を可能にする技術。", category: "Web技術" },
    { id: "pg_196", term: "Responsive Design", reading: "レスポンシブ", definition: "スマホ、PC両方で見やすい設計。", category: "Web技術" },
    { id: "pg_197", term: "CDN", reading: "シーディーエヌ", definition: "ネット上の最適な場所からコンテンツを素早く届ける網。", category: " Web技術" },
    { id: "pg_198", term: "Cross-platform", reading: "クロスプラットフォーム", definition: "1つのコードでiOSとAndroid両方を作る手法。", category: "モバイル" },
    { id: "pg_199", term: "Native SDK", reading: "ネイティブ開発", definition: "特定のOS専用ツールで最高速を目指す開発手法。", category: "モバイル" },
    { id: "pg_200", term: "Beta Version", reading: "ベータ版", definition: "正式リリース前の試験的なバージョン。", category: "開発プロセス" },

    // --- 追加データ (pg_201 - pg_250) ---
    { id: "pg_201", term: "Unit", reading: "ユニット（単位）", definition: "プログラムを構成する最小の機能単位。", category: "開発手法" },
    { id: "pg_202", term: "Regression", reading: "デグレード", definition: "修正によって、以前動いていた場所が壊れること。", category: "開発手法" },
    { id: "pg_203", term: "Code Review", reading: "コードレビュー", definition: "他の開発者が書いたコードをチェックして品質を高めること。", category: "開発手法" },
    { id: "pg_204", term: "Technical Debt", reading: "技術的負債", definition: "その場のしのぎのコードが、将来の負担になること。", category: "開発手法" },
    { id: "pg_205", term: "Lint / Linter", reading: "リンター", definition: "自動でコードの書き間違いやスタイルを直すツール。", category: "開発手法" },
    { id: "pg_206", term: "Formatter", reading: "フォーマッター", definition: "コードの見た目（空白や改行）を自動で整えるツール。", category: "開発手法" },
    { id: "pg_207", term: "Documentation", reading: "ドキュメント化", definition: "使い道や仕組みを説明書として残すこと。", category: "開発手法" },
    { id: "pg_208", term: "QA", reading: "キューエー（品質保証）", definition: "期待通りに動くか確認する検証工程。", category: "開発手法" },
    { id: "pg_209", term: "Scalability", reading: "拡張性（スケーラビリティ）", definition: "ユーザー数が増えても耐えられるようにする能力。", category: "IT全般" },
    { id: "pg_210", term: "Latency", reading: "レイテンシ", definition: "通信や処理の待ち時間（遅延）。", category: "IT全般" },

    { id: "pg_211", term: "Throughput", reading: "スループット", definition: "単位時間あたりに処理できるデータの量。", category: "IT全般" },
    { id: "pg_212", term: "Concurrent", reading: "並行（へいこう）", definition: "複数の処理が切り替わりながら同時に進むこと。", category: "IT全般" },
    { id: "pg_213", term: "Parallel", reading: "並列（へいれつ）", definition: "物理的に完全に同時に複数の処理が進むこと。", category: "IT全般" },
    { id: "pg_214", term: "Cache", reading: "キャッシュ", definition: "一度使ったデータを保存して次回の速度を上げること。", category: "IT全般" },
    { id: "pg_215", term: "Query String", reading: "クエリ文字列", definition: "URLの末尾に「?name=val」形式で渡すデータ。", category: "Web技術" },
    { id: "pg_216", term: "Cookie", reading: "クッキー", definition: "ブラウザに一時的に情報を保存する仕組み（ログイン状態等）。", category: "Web技術" },
    { id: "pg_217", term: "Local Storage", reading: "ローカルストレージ", definition: "ブラウザにより長期間・大きなデータを保存できる仕組み。", category: "Web技術" },
    { id: "pg_218", term: "HTTPS", reading: "エイチティーティーピーエス", definition: "安全（セキュア）に通信できるWebプロトコル。", category: "通信" },
    { id: "pg_219", term: "Header", reading: "ヘッダー", definition: "通信情報の補助データ（端末情報や認証など）。", category: "通信" },
    { id: "pg_220", term: "Status Code", reading: "ステータスコード", definition: "「404 見つからない」等、通信結果を表す3桁の数字。", category: "通信" },

    { id: "pg_221", term: "Git Flow", reading: "ギットフロー", definition: "Gitを使った開発の標準的な手順の型。", category: "バージョン管理" },
    { id: "pg_222", term: "Staging", reading: "ステージング", definition: "コミットする前に変更を選別する領域。", category: "バージョン管理" },
    { id: "pg_223", term: "Fork", reading: "フォーク", definition: "他人のリポジトリを自分のアカウントへコピーすること。", category: "バージョン管理" },
    { id: "pg_224", term: "Revert", reading: "リバート", definition: "以前の変更を取り消して元に戻すこと。", category: "バージョン管理" },
    { id: "pg_225", term: "Squash", reading: "スクワッシュ", definition: "細かすぎる履歴（コミット）を1つにまとめること。", category: "バージョン管理" },
    { id: "pg_226", term: "IDE", reading: "アイディーイー", definition: "統合開発環境。VSCodeなどが代表的。", category: "開発環境" },
    { id: "pg_227", term: "Extension / Plugin", reading: "プラグイン", definition: "後から機能を追加するための部品。", category: "開発環境" },
    { id: "pg_228", term: "Shortcut", reading: "ショートカット", definition: "キーボードだけで素早く操作する機能。", category: "開発環境" },
    { id: "pg_229", term: "Snippets", reading: "スニペット", definition: "よく使うコードの断片を登録して呼び出す機能。", category: "開発環境" },
    { id: "pg_230", term: "Hot Reload", reading: "ホットリロード", definition: "コード保存時に即座に画面を更新する機能。", category: "開発環境" },

    { id: "pg_231", term: "Relational DB", reading: "RDB", definition: "表形式でデータを管理する、最も一般的なDB。", category: "データベース" },
    { id: "pg_232", term: "NoSQL", reading: "ノーエスキューエル", definition: "表形式以外（JSON等）でデータを扱う自由なDB。", category: "データベース" },
    { id: "pg_233", term: "Normalization", reading: "正規化（せいきか）", definition: "データの重複をなくし、DBを効率よく整理すること。", category: "データベース" },
    { id: "pg_234", term: "Index (DB)", reading: "索引（さくいん）", definition: "DBの検索を高速化するための目次。", category: "データベース" },
    { id: "pg_235", term: "Join", reading: "外部結合", definition: "複数のテーブルを1つのデータとしてつなげること。", category: "データベース" },
    { id: "pg_236", term: "Migration", reading: "マイグレーション", definition: "DBの構造をコードで変更・管理すること。", category: "データベース" },
    { id: "pg_237", term: "Seeding", reading: "シーディング", definition: "開発用に初期データ（テストデータ）を流し込むこと。", category: "データベース" },
    { id: "pg_238", term: "PostgreSQL", reading: "ポストグレス", definition: "高機能でオープンソースの代表的なデータベース。", category: "データベース" },
    { id: "pg_239", term: "Redis", reading: "レディス", definition: "メモリ上で爆速で動くキー・バリュー型データベース。", category: "データベース" },
    { id: "pg_240", term: "Backup", reading: "バックアップ", definition: "障害に備えてデータを控えとして複製しておくこと。", category: "保守・運用" },

    { id: "pg_241", term: "Open Source", reading: "OSS", definition: "誰でも自由に中身を見たり改造したりできるソフト。", category: "IT全般" },
    { id: "pg_242", term: "GPL / MIT / Apache", reading: "ライセンス", definition: "ソフトを使っていい条件を定めた規約。", category: "IT全般" },
    { id: "pg_243", term: "SLA", reading: "品質保証合意", definition: "サービスの稼働率などを保証する契約レベル。", category: "保守・運用" },
    { id: "pg_244", term: "Incident", reading: "インシデント", definition: "障害など、本来あるべき状態でない出来事。", category: "保守・運用" },
    { id: "pg_245", term: "Release", reading: "リリース", definition: "公開して一般ユーザーが使えるようにすること。", category: "開発プロセス" },
    { id: "pg_246", term: "Feature", reading: "フィーチャー（機能）", definition: "ソフトウェアが提供する具体的な個々の機能。", category: "開発プロセス" },
    { id: "pg_247", term: "Refactoring", reading: "リファクタリング", definition: "見た目を変えずにコードの健康状態を良くすること。", category: "開発手法" },
    { id: "pg_248", term: "Complexity", reading: "複雑性", definition: "コードの読みづらさや絡まり具合の指標。", category: "設計・理論" },
    { id: "pg_249", term: "Maintainability", reading: "保守性", definition: "修正や機能追加のしやすさ。", category: "設計・理論" },
    { id: "pg_250", term: "Portability", reading: "移植性", definition: "別の環境でもそのまま動かせる能力。", category: "設計・理論" },

    // --- 追加データ (pg_251 - pg_300) -------------------------------------------------------------------
    { id: "pg_251", term: "Markup Language", reading: "マークアップ言語", definition: "文章をタグで囲って構造を定義する。HTML等。", category: "IT基礎" },
    { id: "pg_252", term: "Markdown", reading: "マークダウン", definition: "記号を使って構造化テキストを書く軽量言語。", category: "IT基礎" },
    { id: "pg_253", term: "YAML", reading: "ヤムル", definition: "設定ファイルなどでよく使われる見やすいデータ形式。", category: "IT基礎" },
    { id: "pg_254", term: "CSV", reading: "シーエスブイ", definition: "カンマ区切りで表データを扱うテキスト形式。", category: "IT基礎" },
    { id: "pg_255", term: "XML", reading: "エックスエムエル", definition: "拡張可能なマークアップ言語。設定やデータ交換用。", category: "IT基礎" },
    { id: "pg_256", term: "Base64", reading: "ベース64", definition: "バイナリをテキスト文字列に変換する方式。", category: "IT基礎" },
    { id: "pg_257", term: "Unicode", reading: "ユニコード", definition: "世界中の文字を統一して扱うための文字コード。", category: "IT基礎" },
    { id: "pg_258", term: "UTF-8", reading: "ユーティーエフエイト", definition: "Unicodeの中で最も普及している符号化方式。", category: "IT基礎" },
    { id: "pg_259", term: "Checksum", reading: "チェックサム", definition: "データが壊れていないか確認するための計算値。", category: "IT基礎" },
    { id: "pg_260", term: "Regular Expression", reading: "正規表現", definition: "検索をパワフルに行うための記法。", category: "プログラミング基礎" },

    { id: "pg_261", term: "Overhead", reading: "オーバーヘッド", definition: "本来の処理以外で発生する付随的なコスト。", category: "IT全般" },
    { id: "pg_262", term: "Bottleneck", reading: "ボトルネック", definition: "全体の速度を下げている一番遅い部分。", category: "IT全般" },
    { id: "pg_263", term: "Round Trip", reading: "往復時間", definition: "リクエストして結果が返ってくるまでの往復。", category: "IT全般" },
    { id: "pg_264", term: "State", reading: "ステート（状態）", definition: "プログラムがある瞬間に持っている情報の集まり。", category: "プログラミング基礎" },
    { id: "pg_265", term: "Stateless", reading: "ステートレス", definition: "過去の状態を引き継がずに通信を完結すること。", category: "通信" },
    { id: "pg_266", term: "Session", reading: "セッション", definition: "ログインからログアウトまでの一連の継続的な接続。", category: "Web技術" },
    { id: "pg_267", term: "Transaction", reading: "トランザクション", definition: "不可分な一連の処理のまとまり。", category: "データベース" },
    { id: "pg_268", term: "Rollback", reading: "ロールバック", definition: "失敗したときに前の状態（正常時）に戻すこと。", category: "データベース" },
    { id: "pg_269", term: "Atomic", reading: "アトミック", definition: "それ以上分けられない、あるいは完全に成功か失敗か。", category: "プログラミング基礎" },
    { id: "pg_270", term: "Decoupling", reading: "疎結合（そけつごう）", definition: "部品同士の繋がりを弱くし、個別に変えやすくすること。", category: "設計・理論" },

    { id: "pg_271", term: "Dependency Injection", reading: "DI（依存性の注入）", definition: "外部から必要なものを渡す、きれいな設計手法。", category: "オブジェクト指向" },
    { id: "pg_272", term: "Interface Segregation", reading: "インターフェース分離", definition: "1つの巨大な規約より、小さな規約を複数作ること。", category: "オブジェクト指向" },
    { id: "pg_273", term: "Composition", reading: "コンポジション（合成）", definition: "継承の代わりに、クラスの中に別のクラスを持つこと。", category: "オブジェクト指向" },
    { id: "pg_274", term: "Design Patterns", reading: "デザインパターン", definition: "古くからある、よい設計のひな形集。", category: "設計・理論" },
    { id: "pg_275", term: "Anti-pattern", reading: "アンチパターン", definition: "避けるべき、よくある悪い設計や習慣。", category: "設計・理論" },
    { id: "pg_276", term: "Side Effect", reading: "副作用", definition: "計算以外に、外の変数や画面を書き換えてしまうこと。", category: "プログラミング基礎" },
    { id: "pg_277", term: "Pure Function", reading: "純粋関数", definition: "同じ引数なら必ず同じ結果を返し、副作用がない関数。", category: "プログラミング基礎" },
    { id: "pg_278", term: "First-class Function", reading: "第一級関数", definition: "関数を変数のように自由に扱える性質。", category: "プログラミング基礎" },
    { id: "pg_279", term: "Lazy Loading", reading: "遅延読み込み", definition: "必要になる瞬間までデータの読み込みを後回しにすること。", category: "IT全般" },
    { id: "pg_280", term: "Middleware", reading: "ミドルウェア", definition: "OSとアプリの間で働く便利な中継ソフト。", category: "IT全般" },

    { id: "pg_281", term: "Sandboxing", reading: "サンドボックス", definition: "隔離された安全な環境でプログラムを動かすこと。", category: "セキュリティ" },
    { id: "pg_282", term: "Root", reading: "ルート（特権ユーザー）", definition: "何でもできる管理者。Linux等で使用。", category: "IT全般" },
    { id: "pg_283", term: "Daemon", reading: "デーモン", definition: "裏側で常に起動して待ち受けているソフト。", category: "インフラ" },
    { id: "pg_284", term: "Process", reading: "プロセス", definition: "現在実行されているプログラムの単位。", category: "IT基礎" },
    { id: "pg_285", term: "Thread", reading: "スレッド", definition: "プロセスの中でさらに細かく分かれた、実行の最小単位。", category: "IT基礎" },
    { id: "pg_286", term: "Multithreading", reading: "マルチスレッド", definition: "複数のスレッドを使い、同時に複数の処理をすること。", category: "IT基礎" },
    { id: "pg_287", term: "Race Condition", reading: "データ競合", definition: "同時に書き込みを行ってデータがおかしくなる現象。", category: "不具合" },
    { id: "pg_288", term: "Heap", reading: "ヒープメモリ", definition: "動的に自由に使えるメモリ。管理が難しい。", category: "IT基礎" },
    { id: "pg_289", term: "Stack (Memory)", reading: "スタックメモリ", definition: "関数の呼び出し等で順番に使われる一時メモリ。", category: "IT基礎" },
    { id: "pg_290", term: "Caching Strategy", reading: "キャッシュ戦略", definition: "何をいつ保存し、いつ消すかの戦略。", category: "IT全般" },

    { id: "pg_291", term: "Environment", reading: "環境（エンバイロメント）", definition: "開発、本番、テストなど、プログラムが動く場。", category: "開発プロセス" },
    { id: "pg_292", term: "Production", reading: "プロ本番（プロダクション）", definition: "実際のユーザーが使っている本番の環境。", category: "開発プロセス" },
    { id: "pg_293", term: "Development", reading: "デブ環境（開発用）", definition: "自分の手元でコードを書き、試すための環境。", category: "開発プロセス" },
    { id: "pg_294", term: "Staging", reading: "ステージング環境", definition: "本番公開の直前に、本番そっくりで見せる確認環境。", category: "開発プロセス" },
    { id: "pg_295", term: "Sandbox", reading: "砂場（サンドボックス）", definition: "壊してもいい、実験専用のテスト環境。", category: "開発プロセス" },
    { id: "pg_296", term: "Bug Fix", reading: "バグ修正", definition: "不具合を直し、正常な状態にすること。", category: "保守・運用" },
    { id: "pg_297", term: "Hotfix", reading: "緊急修正", definition: "急を要する重大なトラブルへの即時修正。", category: "保守・運用" },
    { id: "pg_298", term: "Patch", reading: "パッチ", definition: "部分的に当てはめる修正用の小規模コード。", category: "保守・運用" },
    { id: "pg_299", term: "Migration", reading: "移行（マイグレーション）", definition: "古い仕組みから新しい仕組みへ移し替えること。", category: "保守・運用" },
    { id: "pg_300", term: "Abstraction Level", reading: "詳細度 / 抽象レベル", definition: "どれだけ具体的な細部を見ているか（高レベル・低レベル）。", category: "設計・理論" }
];
